server:
  port: 8099

spring:
  application:
    name: mvc-test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/glucacxe?useSSL=false&serverTimezone=UTC
    username: root
    password: abc123


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml
